@startuml

package "aybk" {
    class app {
        + add(a: int, b: int): int
    }
}

package "tests" {
    class test_app {
        + test_add()
    }
}

test_app --> app : imports / uses add()

@enduml


